// Generated by mecha-manifest. Enhancement only:
// the page books identically with this file blocked.
(function () {
  "use strict";
  var config = {};
  try { config = JSON.parse(document.getElementById("booking-config").textContent); } catch (e) {}

  // 1. Times in the visitor's zone — every stamp and the zone line together,
  // or nothing: a page half-converted is worse than a labelled host zone.
  var zone = config.timezone;
  try {
    var detected = Intl.DateTimeFormat().resolvedOptions().timeZone;
    if (detected && detected !== config.timezone) {
      zone = detected;
      var fmt = new Intl.DateTimeFormat(undefined,
        { hour: "numeric", minute: "2-digit", timeZone: zone });
      document.querySelectorAll(".when[data-utc]").forEach(function (el) {
        el.textContent = fmt.format(new Date(el.getAttribute("data-utc"))).toLowerCase();
      });
      var note = document.getElementById("zone-note");
      if (note) {
        note.textContent = "Times are shown in your time zone (" + zone +
          " — currently " + fmt.format(new Date()).toLowerCase() + ").";
      }
    }
  } catch (e) { zone = config.timezone; /* the server-rendered labels stand */ }

  // 2. The picked time, echoed in full above the details — the reveal is
  // CSS; this chip is the only part a script writes, and losing it loses a
  // restatement, never the booking.
  var picked = document.getElementById("picked");
  var describe = function (input) {
    var raw = input.value.split("|");
    var start = new Date(raw[0]);
    var minutes = parseInt(raw[1], 10) || 0;
    var end = new Date(start.getTime() + minutes * 60000);
    try {
      var day = new Intl.DateTimeFormat(undefined,
        { weekday: "long", month: "short", day: "numeric", timeZone: zone });
      var time = new Intl.DateTimeFormat(undefined,
        { hour: "numeric", minute: "2-digit", timeZone: zone });
      return day.format(start) + " · " + time.format(start).toLowerCase() +
        " – " + time.format(end).toLowerCase() + " (" + minutes + " min)";
    } catch (e) { return ""; }
  };
  var updatePicked = function () {
    if (!picked) return;
    var checked = document.querySelector('input[name="_slot"]:checked');
    picked.textContent = checked ? describe(checked) : "";
  };
  document.addEventListener("change", function (event) {
    if (event.target && event.target.name === "_slot") updatePicked();
  });
  updatePicked(); // a rejected submission arrives with its slot re-checked

  // 3. Live availability. The page polls the same truth the POST checks, so
  // a slot someone else just held leaves the page instead of waiting to fail
  // at submit; if it was *your* pick, the page says so out loud. New slots
  // (a freed cancellation, a fresh push) reload a pristine page — anything
  // typed makes the reload an offer instead, never a theft.
  var note = document.getElementById("live-note");
  if (config.slots_url && note && window.fetch) {
    var dirty = false;
    document.addEventListener("input", function (event) {
      if (event.target && event.target.closest && event.target.closest(".details")) dirty = true;
    });
    var hostDay = null;
    try {
      hostDay = new Intl.DateTimeFormat("en-CA",
        { timeZone: config.timezone, year: "numeric", month: "2-digit", day: "2-digit" });
    } catch (e) {}
    var inShownWeek = function (iso) {
      if (!hostDay || !config.week_start) return false;
      var day = hostDay.format(new Date(iso));
      return day >= config.week_start && day < config.week_end;
    };
    var tell = function (message, withReload) {
      note.textContent = message;
      if (withReload) {
        var link = document.createElement("a");
        link.href = window.location.href;
        link.textContent = "Show them";
        note.appendChild(document.createTextNode(" — "));
        note.appendChild(link);
      }
      note.hidden = false;
    };
    var sweep = function (offered) {
      var open = {};
      offered.forEach(function (s) { open[s.start + "|" + s.duration_minutes] = true; });
      var shown = {};
      var pickTaken = false;
      document.querySelectorAll('.week input[name="_slot"]').forEach(function (input) {
        var slot = input.closest(".slot");
        if (!slot || slot.classList.contains("gone")) return;
        if (open[input.value]) { shown[input.value] = true; return; }
        if (input.checked) { input.checked = false; pickTaken = true; }
        slot.classList.add("gone");
        window.setTimeout(function () {
          var day = slot.closest(".day");
          slot.remove();
          if (day && !day.querySelector(".slot")) day.remove();
        }, 350);
      });
      if (pickTaken) {
        updatePicked();
        tell("That time was just taken — these are still open.");
      }
      var fresh = offered.some(function (s) {
        return s.duration_minutes === config.duration &&
          !shown[s.start + "|" + s.duration_minutes] &&
          inShownWeek(s.start) && new Date(s.start) > new Date();
      });
      if (fresh) {
        var untouched = !dirty && !document.querySelector('input[name="_slot"]:checked');
        if (untouched) { window.location.reload(); }
        else if (note.hidden) { tell("More times just opened up.", true); }
      }
    };
    var refresh = function () {
      fetch(config.slots_url, { headers: { Accept: "application/json" } })
        .then(function (res) { return res.ok ? res.json() : null; })
        .then(function (data) { if (data && data.slots) sweep(data.slots); })
        .catch(function () { /* offline is not an error the page can fix */ });
    };
    window.setInterval(refresh, 30000);
    document.addEventListener("visibilitychange", function () {
      if (document.visibilityState === "visible") refresh();
    });
  }
})();
