// Generated by mecha-manifest. Enhancement only:
// the page books identically with this file blocked.
(function () {
  "use strict";
  var config = {};
  try { config = JSON.parse(document.getElementById("booking-config").textContent); } catch (e) {}

  // 1. Times in the visitor's zone — every stamp and the zone line together,
  // or nothing: a page half-converted is worse than a labelled host zone.
  try {
    var zone = Intl.DateTimeFormat().resolvedOptions().timeZone;
    if (zone && zone !== config.timezone) {
      var whens = document.querySelectorAll(".when[data-utc]");
      var fmt = new Intl.DateTimeFormat(undefined,
        { hour: "numeric", minute: "2-digit", timeZone: zone });
      whens.forEach(function (el) {
        el.textContent = fmt.format(new Date(el.getAttribute("data-utc"))).toLowerCase();
      });
      var nowFmt = new Intl.DateTimeFormat(undefined,
        { hour: "numeric", minute: "2-digit", timeZone: zone });
      var note = document.getElementById("zone-note");
      if (note) {
        note.textContent = "Times are shown in your time zone (" + zone +
          " — currently " + nowFmt.format(new Date()).toLowerCase() + ").";
      }
    }
  } catch (e) { /* the server-rendered labels stand */ }

  // 2. The duration filter, built only when there is something to filter.
  var minutes = [];
  document.querySelectorAll(".slot .mins[data-minutes]").forEach(function (el) {
    var m = el.getAttribute("data-minutes");
    if (minutes.indexOf(m) < 0) minutes.push(m);
  });
  var week = document.querySelector(".week");
  if (week && minutes.length > 1) {
    minutes.sort(function (a, b) { return a - b; });
    var bar = document.createElement("div");
    bar.className = "durations";
    bar.setAttribute("role", "group");
    bar.setAttribute("aria-label", "Meeting length");
    var apply = function (wanted) {
      document.querySelectorAll(".slot").forEach(function (slot) {
        var m = slot.querySelector(".mins").getAttribute("data-minutes");
        var show = wanted === null || m === wanted;
        slot.hidden = !show;
        if (!show) {
          var input = slot.querySelector("input");
          if (input.checked) input.checked = false;
        }
      });
      bar.querySelectorAll("button").forEach(function (b) {
        b.setAttribute("aria-pressed", String(b.dataset.minutes === (wanted === null ? "all" : wanted)));
      });
    };
    var mk = function (label, value) {
      var b = document.createElement("button");
      b.type = "button";
      b.textContent = label;
      b.dataset.minutes = value === null ? "all" : value;
      b.addEventListener("click", function () { apply(value); });
      bar.appendChild(b);
      return b;
    };
    minutes.forEach(function (m) { mk(m + " min", m); });
    mk("all", null).setAttribute("aria-pressed", "true");
    week.parentNode.insertBefore(bar, week);
  }
})();
