// Generated by mecha-manifest. Mirrors Condition::holds in condition.rs —
// keep the two in step, including the cases that look like mistakes.
(function () {
  var node = document.getElementById('conditions');
  if (!node) return;
  var rules = JSON.parse(node.textContent || '{}');
  var form = document.querySelector('form');
  if (!form) return;

  function raw(name) {
    var els = form.querySelectorAll('[name="' + CSS.escape(name) + '"]');
    if (!els.length) return undefined;
    var first = els[0];
    if (first.type === 'checkbox') {
      if (els.length > 1) {
        var picked = [];
        els.forEach(function (el) { if (el.checked) picked.push(el.value); });
        return picked;
      }
      return first.checked;
    }
    return first.value;
  }

  function present(v) {
    if (v === undefined || v === null) return false;
    if (typeof v === 'string') return v.trim() !== '';
    if (Array.isArray(v)) return v.length > 0;
    return true;
  }

  function num(v) {
    if (typeof v === 'number') return v;
    if (typeof v === 'string' && v.trim() !== '') {
      var n = Number(v.trim());
      return isNaN(n) ? null : n;
    }
    return null;
  }

  function holds(rule) {
    var a = raw(rule.field);
    var b = rule.value;
    switch (rule.op) {
      case 'present': return present(a);
      case 'absent': return !present(a);
      case 'is_true': return a === true;
      case 'is_false': return a === false;
      case 'eq': return a !== undefined && a === b;
      case 'ne': return a !== undefined && a !== b;
      case 'in': return a !== undefined && Array.isArray(b) && b.indexOf(a) !== -1;
      case 'not_in': return a !== undefined && Array.isArray(b) && b.indexOf(a) === -1;
      case 'gt': case 'gte': case 'lt': case 'lte': {
        var x = num(a), y = num(b);
        if (x === null || y === null) return false;
        if (rule.op === 'gt') return x > y;
        if (rule.op === 'gte') return x >= y;
        if (rule.op === 'lt') return x < y;
        return x <= y;
      }
      default: return false;
    }
  }

  // A hidden control must not submit a value, or the server rejects the
  // record as carrying a field that was never shown. `disabled` is what
  // stops a browser sending it; `hidden` alone does not.
  function apply() {
    Object.keys(rules).forEach(function (key) {
      var parts = key.split(':');
      var selector = parts[0] === 'step'
        ? '[data-step="' + CSS.escape(parts[1]) + '"]'
        : '[data-field="' + CSS.escape(parts[1]) + '"]';
      var el = form.querySelector(selector);
      if (!el) return;
      var show = holds(rules[key]);
      el.hidden = !show;
      el.querySelectorAll('input, select, textarea').forEach(function (control) {
        control.disabled = !show;
      });
    });
  }

  form.addEventListener('input', apply);
  form.addEventListener('change', apply);
  apply();
})();
