// Generated by mecha-manifest. Enhancement only:
// the poll answers identically with this file blocked.
(function () {
  "use strict";
  var grid = document.querySelector(".week.poll");
  var form = grid && grid.closest("form");
  if (!grid || !form || !window.fetch) return;
  var cells = Array.prototype.slice.call(grid.querySelectorAll(".slot.answer"));
  // A closed poll is read-only and stays exactly as rendered.
  if (!cells.length || cells[0].querySelector("input[disabled]")) return;

  var ORDER = ["yes", "if_needed", "no"];
  var WORDS = { yes: "yes", if_needed: "if needed", no: "no" };

  var stateOf = function (cell) {
    var checked = cell.querySelector("input:checked");
    return checked ? checked.value : "no";
  };
  var paint = function (cell, state) {
    var input = cell.querySelector('input[value="' + state + '"]');
    if (input) input.checked = true;
    cell.setAttribute("data-state", state);
    cell.querySelector(".state").textContent = WORDS[state];
    var when = cell.querySelector(".when");
    var len = cell.querySelector(".len");
    cell.setAttribute("aria-label",
      (when ? when.textContent : "") + (len ? " " + len.textContent : "") +
      " — your answer: " + WORDS[state] + ". Press to change.");
  };
  var apply = function (cell, state) {
    if (stateOf(cell) === state && cell.getAttribute("data-state") === state) return;
    paint(cell, state);
    queueSave();
  };

  grid.classList.add("paint");
  form.classList.add("autosaves");
  cells.forEach(function (cell) {
    var chip = document.createElement("span");
    chip.className = "state";
    cell.appendChild(chip);
    cell.setAttribute("role", "button");
    cell.setAttribute("tabindex", "0");
    paint(cell, stateOf(cell));
  });

  // Tap cycles one cell; a drag paints every cell it crosses with the state
  // the first tap produced — the anchor decides the stroke, so a mixed drag
  // never flickers (when2meet's own mechanic).
  var stroke = null;
  var cellAt = function (event) {
    var el = document.elementFromPoint(event.clientX, event.clientY);
    return el && el.closest ? el.closest(".slot.answer") : null;
  };
  grid.addEventListener("pointerdown", function (event) {
    var cell = cellAt(event);
    if (!cell) return;
    event.preventDefault();
    stroke = ORDER[(ORDER.indexOf(stateOf(cell)) + 1) % ORDER.length];
    apply(cell, stroke);
    try { grid.setPointerCapture(event.pointerId); } catch (e) {}
  });
  grid.addEventListener("pointermove", function (event) {
    if (stroke === null) return;
    var cell = cellAt(event);
    if (cell) apply(cell, stroke);
  });
  ["pointerup", "pointercancel"].forEach(function (name) {
    grid.addEventListener(name, function () { stroke = null; });
  });
  grid.addEventListener("keydown", function (event) {
    if (event.key !== " " && event.key !== "Enter") return;
    var cell = event.target.closest && event.target.closest(".slot.answer");
    if (!cell) return;
    event.preventDefault();
    apply(cell, ORDER[(ORDER.indexOf(stateOf(cell)) + 1) % ORDER.length]);
  });

  // Autosave: every commit POSTs, debounced. A failed save says so and
  // hands back the button — the JS-off path is also the degraded path.
  var status = document.getElementById("savestate");
  var timer = null;
  var inflight = false;
  var again = false;
  var say = function (text) {
    if (status) { status.hidden = false; status.textContent = text; }
  };
  var fallback = function () {
    say("Couldn’t save — use the button below.");
    form.classList.remove("autosaves");
  };
  var save = function () {
    if (inflight) { again = true; return; }
    inflight = true;
    var body = new URLSearchParams(new FormData(form));
    fetch(window.location.pathname, {
      method: "POST", body: body, headers: { Accept: "application/json" }
    })
      .then(function (res) {
        if (res.status === 204) say("Saved — you can change your answers until the poll closes.");
        else fallback();
      })
      .catch(fallback)
      .then(function () {
        inflight = false;
        if (again) { again = false; save(); }
      });
  };
  var queueSave = function () {
    if (timer) window.clearTimeout(timer);
    say("Saving…");
    timer = window.setTimeout(save, 700);
  };
})();
