// Generated by mecha-manifest. Enhancement only:
// the screen answers identically with this file blocked, one reload behind.
(function () {
  "use strict";
  if (!window.fetch) return;
  var refresh = function () {
    fetch(window.location.pathname + "/data.json", {
      headers: { Accept: "application/json" }
    })
      .then(function (res) { return res.ok ? res.json() : null; })
      .then(function (data) {
        if (!data) return;
        var count = document.getElementById("screen-count");
        if (count && data.count) count.textContent = data.count;
        var slots = data.results || {};
        Object.keys(slots).forEach(function (qid) {
          var slot = document.getElementById("results-q-" + qid);
          if (slot && slot.innerHTML !== slots[qid]) slot.innerHTML = slots[qid];
        });
      })
      .catch(function () { /* offline is not an error the wall can fix */ });
  };
  window.setInterval(refresh, 2000);
  document.addEventListener("visibilitychange", function () {
    if (document.visibilityState === "visible") refresh();
  });
})();
