// Generated by mecha-manifest. Enhancement only:
// the survey answers identically with this file blocked.
(function () {
  "use strict";
  var form = document.querySelector("form.survey");
  if (!form || !window.fetch) return;
  // A closed survey is read-only and stays exactly as rendered.
  if (!form.querySelector("button[type=submit]")) return;
  var live = form.getAttribute("data-live") === "1";

  var status = document.getElementById("savestate");
  var say = function (text) {
    if (status) { status.hidden = false; status.textContent = text; }
  };

  // Live results: swap each question's fragment only when it changed, so
  // an open <details> in an unchanged block is not slammed shut.
  var refreshResults = function () {
    if (!live) return;
    fetch(window.location.pathname + "/results.json", {
      headers: { Accept: "application/json" }
    })
      .then(function (res) { return res.ok ? res.json() : null; })
      .then(function (data) {
        if (!data) return;
        var intro = document.querySelector(".intro");
        if (intro && data.intro) intro.textContent = data.intro;
        if (!data.results) return;
        var when = document.getElementById("results-when");
        if (when) when.hidden = true;
        Object.keys(data.results).forEach(function (qid) {
          var slot = document.getElementById("results-q-" + qid);
          if (slot && slot.innerHTML !== data.results[qid]) {
            slot.innerHTML = data.results[qid];
          }
        });
      })
      .catch(function () { /* offline is not an error the page can fix */ });
  };

  // Autosave: every commit POSTs, debounced; a failed save says so and
  // hands back the button — the JS-off path is also the degraded path. A
  // 204 refreshes results immediately: the voter who just voted sees
  // their bar tick up now, not at the next interval.
  var autosave = true;
  var timer = null, inflight = false, again = false;
  var fallback = function () {
    say("Couldn’t save — use the button below.");
    autosave = false;
  };
  var save = function () {
    if (!autosave) return;
    if (inflight) { again = true; return; }
    inflight = true;
    var body = new URLSearchParams(new FormData(form));
    fetch(window.location.pathname, {
      method: "POST", body: body, headers: { Accept: "application/json" }
    })
      .then(function (res) {
        if (res.status === 204) {
          say("Saved — you can change your answers until the poll closes.");
          refreshResults();
        } else if (res.status === 409) {
          say("This poll just closed; answers can no longer change.");
          autosave = false;
        } else fallback();
      })
      .catch(fallback)
      .then(function () {
        inflight = false;
        if (again) { again = false; save(); }
      });
  };
  var queueSave = function () {
    if (!autosave) return;
    if (timer) window.clearTimeout(timer);
    say("Saving…");
    timer = window.setTimeout(save, 700);
  };
  form.addEventListener("change", queueSave);
  form.addEventListener("input", function (event) {
    var target = event.target;
    if (!target) return;
    if (target.tagName === "TEXTAREA" || target.type === "number") queueSave();
  });

  if (live) {
    window.setInterval(refreshResults, 10000);
    document.addEventListener("visibilitychange", function () {
      if (document.visibilityState === "visible") refreshResults();
    });
  }
})();
