// Generated by mecha-manifest. Enhancement only:
// the survey answers identically with this file blocked.
(function () {
  "use strict";
  var form = document.querySelector("form.survey");
  if (!form || !window.fetch) return;
  // A closed survey is read-only and stays exactly as rendered.
  if (!form.querySelector("button[type=submit]")) return;
  var live = form.getAttribute("data-live") === "1";
  // A specimen with no server behind it (the gallery). The widgets below
  // still upgrade; every path that would touch the network is off, because
  // a POST to a static file comes back as "Couldn't save" the moment
  // anyone drags a row.
  var demo = form.getAttribute("data-demo") === "1";

  var status = document.getElementById("savestate");
  var say = function (text) {
    if (status) { status.hidden = false; status.textContent = text; }
  };

  // Live results: swap each question's fragment only when it changed, so
  // an open <details> in an unchanged block is not slammed shut.
  var refreshResults = function () {
    if (!live) return;
    fetch(window.location.pathname + "/results.json", {
      headers: { Accept: "application/json" }
    })
      .then(function (res) { return res.ok ? res.json() : null; })
      .then(function (data) {
        if (!data) return;
        var intro = document.querySelector(".intro");
        if (intro && data.intro) intro.textContent = data.intro;
        if (!data.results) return;
        var when = document.getElementById("results-when");
        if (when) when.hidden = true;
        Object.keys(data.results).forEach(function (qid) {
          var slot = document.getElementById("results-q-" + qid);
          if (slot && slot.innerHTML !== data.results[qid]) {
            slot.innerHTML = data.results[qid];
          }
        });
      })
      .catch(function () { /* offline is not an error the page can fix */ });
  };

  // Autosave: every commit POSTs, debounced; a failed save says so and
  // hands back the button — the JS-off path is also the degraded path. A
  // 204 refreshes results immediately: the voter who just voted sees
  // their bar tick up now, not at the next interval.
  var autosave = !demo;
  var timer = null, inflight = false, again = false;
  var fallback = function () {
    say("Couldn’t save — use the button below.");
    autosave = false;
  };
  var save = function () {
    if (!autosave) return;
    if (inflight) { again = true; return; }
    inflight = true;
    var body = new URLSearchParams(new FormData(form));
    fetch(window.location.pathname, {
      method: "POST", body: body, headers: { Accept: "application/json" }
    })
      .then(function (res) {
        if (res.status === 204) {
          say("Saved — you can change your answers until the poll closes.");
          refreshResults();
        } else if (res.status === 409) {
          say("This poll just closed; answers can no longer change.");
          autosave = false;
        } else fallback();
      })
      .catch(fallback)
      .then(function () {
        inflight = false;
        if (again) { again = false; save(); }
      });
  };
  var queueSave = function () {
    if (!autosave) return;
    if (timer) window.clearTimeout(timer);
    say("Saving…");
    timer = window.setTimeout(save, 700);
  };
  form.addEventListener("change", queueSave);
  form.addEventListener("input", function (event) {
    var target = event.target;
    if (!target) return;
    if (target.tagName === "TEXTAREA" || target.type === "number") queueSave();
  });

  // --- the VAS track --------------------------------------------------
  // A range input laid over the number field, thumbless until touched:
  // a slider with a resting place would anchor answers to it, and an
  // untouched control submitting 50 would invent a midpoint. The number
  // input keeps the name and the keyboard path; the track only writes
  // into it, so the form posts exactly what JS-off would.
  Array.prototype.forEach.call(
    form.querySelectorAll(".vas input[type=number]"),
    function (num) {
      var range = document.createElement("input");
      range.type = "range";
      range.min = "0";
      range.max = "100";
      range.className = "vas-range";
      range.setAttribute("aria-hidden", "true");
      range.tabIndex = -1;
      if (num.value !== "") {
        range.value = num.value;
      } else {
        range.value = "50";
        range.className += " untouched";
      }
      num.classList.add("vas-number");
      num.parentNode.insertBefore(range, num);
      range.addEventListener("input", function () {
        range.classList.remove("untouched");
        num.value = range.value;
        queueSave();
      });
      num.addEventListener("input", function () {
        if (num.value === "") return;
        range.value = num.value;
        range.classList.remove("untouched");
      });
    }
  );

  // --- ranking by buttons ---------------------------------------------
  // The rank selects give way to a list with move buttons and a polite
  // live region — the poll grid's ARIA discipline applied to a list.
  // Moving anything expresses a full order, so every select is synced to
  // the list; partial rankings remain the JS-off affordance. (Drag can
  // arrive later; the buttons are the accessible spine either way.)
  Array.prototype.forEach.call(
    form.querySelectorAll(".survey .question, section.question"),
    function (section) {
      var labels = section.querySelectorAll("label.opt.rank");
      if (!labels.length) return;
      var rows = Array.prototype.map.call(labels, function (label, index) {
        var sel = label.querySelector("select");
        return {
          sel: sel,
          name: label.querySelector(".optlabel").textContent,
          rank: sel.value === "" ? null : parseInt(sel.value, 10),
          declared: index
        };
      });
      rows.sort(function (a, b) {
        if (a.rank !== null && b.rank !== null) return a.rank - b.rank;
        if (a.rank !== null) return -1;
        if (b.rank !== null) return 1;
        return a.declared - b.declared;
      });

      var list = document.createElement("ol");
      list.className = "rank-list";
      var live = document.createElement("p");
      live.className = "visually-hidden";
      live.setAttribute("aria-live", "polite");
      section.classList.add("ranks-enhanced");
      labels[0].parentNode.insertBefore(list, labels[0]);
      section.appendChild(live);

      var sync = function () {
        rows.forEach(function (row, index) {
          row.sel.value = String(index + 1);
        });
        queueSave();
      };
      var announce = function (row) {
        live.textContent =
          row.name + " is now " + (rows.indexOf(row) + 1) + " of " + rows.length + ".";
      };
      var render = function (focus) {
        list.textContent = "";
        rows.forEach(function (row, index) {
          var item = document.createElement("li");
          item.rowRef = row;
          // The grip is the drag surface — pointer capture makes the
          // stroke survive leaving the row (the paint grid's mechanic),
          // and `touch-action:none` lives on the grip alone so the rest
          // of the page still scrolls under a thumb. Buttons remain the
          // keyboard's path; the grip is decoration to a screen reader.
          var grip = document.createElement("span");
          grip.className = "grip";
          grip.textContent = "⠿";
          grip.setAttribute("aria-hidden", "true");
          var name = document.createElement("span");
          name.className = "optlabel";
          name.textContent = row.name;
          var up = document.createElement("button");
          up.type = "button";
          up.textContent = "↑";
          up.setAttribute("aria-label", "Move " + row.name + " up");
          up.disabled = index === 0;
          var down = document.createElement("button");
          down.type = "button";
          down.textContent = "↓";
          down.setAttribute("aria-label", "Move " + row.name + " down");
          down.disabled = index === rows.length - 1;
          var move = function (delta) {
            var to = index + delta;
            rows.splice(to, 0, rows.splice(index, 1)[0]);
            announce(row);
            sync();
            render({ row: row, dir: delta });
          };
          up.addEventListener("click", function () { move(-1); });
          down.addEventListener("click", function () { move(1); });

          grip.addEventListener("pointerdown", function (event) {
            event.preventDefault();
            try { grip.setPointerCapture(event.pointerId); } catch (e) {}
            item.classList.add("dragging");
          });
          grip.addEventListener("pointermove", function (event) {
            if (!item.classList.contains("dragging")) return;
            var el = document.elementFromPoint(event.clientX, event.clientY);
            var over = el && el.closest ? el.closest(".rank-list li") : null;
            if (!over || over === item || over.parentNode !== list) return;
            var kids = Array.prototype.slice.call(list.children);
            if (kids.indexOf(over) < kids.indexOf(item)) {
              list.insertBefore(item, over);
            } else {
              list.insertBefore(item, over.nextSibling);
            }
          });
          var drop = function () {
            if (!item.classList.contains("dragging")) return;
            item.classList.remove("dragging");
            // The DOM is where the drag happened; make it the order.
            var order = Array.prototype.map.call(list.children, function (li) {
              return li.rowRef;
            });
            rows.length = 0;
            Array.prototype.push.apply(rows, order);
            announce(row);
            sync();
            render(null);
          };
          grip.addEventListener("pointerup", drop);
          grip.addEventListener("pointercancel", drop);

          item.appendChild(grip);
          item.appendChild(up);
          item.appendChild(down);
          item.appendChild(name);
          list.appendChild(item);
          // Focus follows the moved row, so arrows keep working from the
          // keyboard without re-tabbing to it.
          if (focus && focus.row === row) {
            (focus.dir < 0 ? up : down).focus();
          }
        });
      };
      render(null);
    }
  );

  if (live) {
    window.setInterval(refreshResults, 10000);
    document.addEventListener("visibilitychange", function () {
      if (document.visibilityState === "visible") refreshResults();
    });
  }
})();
